export const ACTIONS = {
    GET_INITIAL_DATA: 'GET_INITIAL_DATA',
    GET_INITIAL_DATA_SUCESS: 'GET_INITIAL_DATA_SUCESS',
    GET_INDIVIDUAL_CONVERSATION_HISTORY: 'GET_INDIVIDUAL_CONVERSATION_HISTORY',
    GET_INDIVIDUAL_CONVERSATION_HISTORY_SUCESS: 'GET_INDIVIDUAL_CONVERSATION_HISTORY_SUCESS',
    SEND_INDIVIDUAL_MESSAGE: 'SEND_INDIVIDUAL_MESSAGE',
    SET_CURRENT_MODE_DETAILS: 'SET_CURRENT_MODE_DETAILS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SEND_INDIVIDUAL_CONVERSATION_HISTORY_SUCESS: 'SEND_INDIVIDUAL_CONVERSATION_HISTORY_SUCESS',
    GET_GROUP_CONVERSATION_HISTORY: 'GET_GROUP_CONVERSATION_HISTORY',
    GET_GROUP_CONVERSATION_HISTORY_SUCCESS: 'GET_GROUP_CONVERSATION_HISTORY_SUCCESS',
    CREATE_GROUP: 'CREATE_GROUP',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    SEND_GROUP_MESSAGE: 'SEND_GROUP_MESSAGE'
}
